version: 0.2

phases:
    install:
        runtime-versions:
            docker: 18
    pre_build:
        commands:
            - echo npm install start
            - npm i
            - echo npm install complete
    build:
        commands:
            - echo cypress test start
            - npx cypress run --headless
            - echo cypress test completed.
